{
 "title": "Teste1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Análise de Fluxo (Gráfico Temporal de Ocupação)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mtimdparking",
     "rawSql": "SELECT\n  $__timeGroup(time_index, '1m') AS \"time\",\n  count(entity_id) AS \"Vagas Ocupadas\"\nFROM mtimdparking.etparkingspot\nWHERE s = 'Ocupada'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "O Painel Público (Status Atual das Vagas)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "dataset": "mtimdparking",
     "rawSql": "SELECT\n  entity_id AS \"Vaga\",\n  s AS \"Status\"\nFROM mtimdparking.etparkingspot\nWHERE time_index IN (\n    SELECT MAX(time_index)\n    FROM mtimdparking.etparkingspot\n    GROUP BY entity_id\n)\nORDER BY entity_id ASC"
    }
   ]
  },
  {
   "title": "Visor da Recepção (Tabela de Infrações)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "mtimdparking",
     "rawSql": "SELECT\n  time_index AS \"Horário\",\n  entity_id AS \"Vaga\",\n  p AS \"Placa Infratora\"\nFROM mtimdparking.etparkingspot\nWHERE p NOT IN ('sem_placa', 'OK')\nORDER BY time_index DESC\nLIMIT 10"
    }
   ]
  }
 ]
}